# -*- coding: utf-8 -*-
"""Document export tools for DOCX, PPTX, and PDF artifacts."""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Optional, TYPE_CHECKING

from app.xuanwu.tools.base import ToolResult
from app.xuanwu.tools.filesystem.present_tool import present_files_tool
from app.xuanwu.tools.work_dir_guard import resolve_file_path

if TYPE_CHECKING:
    from pydantic_ai import RunContext
    from app.xuanwu.core.deps import SkillDeps


def _resolve_export_path(
    ctx: "RunContext[SkillDeps]",
    file_path: str,
    suffix: str,
) -> Path:
    path = resolve_file_path(ctx, file_path)
    if not path.suffix:
        path = path.with_suffix(suffix)
    elif path.suffix.lower() != suffix.lower():
        raise ValueError(f"file extension must be {suffix}: {file_path}")
    return path


def _ensure_parent_dir(path: Path) -> None:
    parent = path.parent
    parent.mkdir(parents=True, exist_ok=True)


async def _try_present_path(
    ctx: "RunContext[SkillDeps]",
    path: Path,
    *,
    auto_present: bool,
) -> tuple[bool, Optional[str], list[str]]:
    if not auto_present:
        return False, None, []

    result = await present_files_tool(ctx, [str(path)])
    details = result.get("details") if isinstance(result, dict) else None
    presented_paths = (
        details.get("presented_relative_paths")
        if isinstance(details, dict)
        else None
    )
    normalized_paths = (
        [str(item) for item in presented_paths if isinstance(item, str)]
        if isinstance(presented_paths, list)
        else []
    )
    if result.get("is_error"):
        return False, str(result.get("error") or "failed to present file"), normalized_paths
    return True, None, normalized_paths


def _write_docx(path: Path, *, title: str, content: str) -> None:
    try:
        from docx import Document
    except ImportError as exc:  # pragma: no cover - dependency guard
        raise RuntimeError("python-docx is not installed") from exc

    doc = Document()
    if title.strip():
        doc.add_heading(title.strip(), level=1)

    blocks = [item.strip() for item in str(content or "").split("\n\n") if item.strip()]
    if not blocks:
        blocks = [""]
    for block in blocks:
        doc.add_paragraph(block)
    doc.save(str(path))


def _write_pptx(path: Path, *, title: str, bullet_points: list[str], content: str) -> None:
    try:
        from pptx import Presentation
    except ImportError as exc:  # pragma: no cover - dependency guard
        raise RuntimeError("python-pptx is not installed") from exc

    presentation = Presentation()
    slide = presentation.slides.add_slide(presentation.slide_layouts[1])
    slide_title = title.strip() or "Presentation"
    slide.shapes.title.text = slide_title

    text_frame = slide.shapes.placeholders[1].text_frame
    text_frame.clear()
    points = [item.strip() for item in bullet_points if isinstance(item, str) and item.strip()]
    if not points:
        points = [line.strip() for line in str(content or "").splitlines() if line.strip()]
    if not points:
        points = ["Generated by XuanWu"]

    text_frame.text = points[0]
    for point in points[1:]:
        paragraph = text_frame.add_paragraph()
        paragraph.text = point
        paragraph.level = 0

    presentation.save(str(path))


def _write_pdf(path: Path, *, title: str, content: str) -> None:
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas
    except ImportError as exc:  # pragma: no cover - dependency guard
        raise RuntimeError("reportlab is not installed") from exc

    pdf = canvas.Canvas(str(path), pagesize=letter)
    page_width, page_height = letter
    margin = 72
    y = page_height - margin

    if title.strip():
        pdf.setFont("Helvetica-Bold", 16)
        pdf.drawString(margin, y, title.strip())
        y -= 28

    pdf.setFont("Helvetica", 11)
    paragraphs = str(content or "").split("\n")
    if not paragraphs:
        paragraphs = [""]
    for paragraph in paragraphs:
        lines = textwrap.wrap(paragraph, width=95) or [""]
        for line in lines:
            if y <= margin:
                pdf.showPage()
                pdf.setFont("Helvetica", 11)
                y = page_height - margin
            pdf.drawString(margin, y, line)
            y -= 16
        y -= 4

    pdf.save()


def _success_result(
    *,
    message: str,
    requested_path: str,
    output_path: Path,
    export_format: str,
    presented: bool,
    present_error: Optional[str],
    presented_relative_paths: list[str],
) -> dict:
    details = {
        "file_path": requested_path,
        "output_path": str(output_path),
        "bytes_written": output_path.stat().st_size if output_path.exists() else 0,
        "format": export_format,
        "presented": presented,
        "presented_relative_paths": presented_relative_paths,
    }
    if present_error:
        details["present_error"] = present_error

    return ToolResult.text(message, details=details).to_dict()


async def export_docx_tool(
    ctx: "RunContext[SkillDeps]",
    file_path: str,
    title: str = "",
    content: str = "",
    auto_present: bool = True,
) -> dict:
    """Export content into a DOCX document under user work_dir."""
    try:
        output_path = _resolve_export_path(ctx, file_path, ".docx")
    except ValueError as e:
        return ToolResult.error(str(e), details={"file_path": file_path}).to_dict()

    try:
        _ensure_parent_dir(output_path)
        _write_docx(output_path, title=title, content=content)
        presented, present_error, presented_paths = await _try_present_path(
            ctx,
            output_path,
            auto_present=auto_present,
        )
        return _success_result(
            message=f"DOCX exported: {output_path.name}",
            requested_path=file_path,
            output_path=output_path,
            export_format="docx",
            presented=presented,
            present_error=present_error,
            presented_relative_paths=presented_paths,
        )
    except Exception as e:
        return ToolResult.error(str(e), details={"file_path": file_path}).to_dict()


async def export_pptx_tool(
    ctx: "RunContext[SkillDeps]",
    file_path: str,
    title: str = "",
    bullet_points: Optional[list[str]] = None,
    content: str = "",
    auto_present: bool = True,
) -> dict:
    """Export bullet-point content into a PPTX slide deck."""
    try:
        output_path = _resolve_export_path(ctx, file_path, ".pptx")
    except ValueError as e:
        return ToolResult.error(str(e), details={"file_path": file_path}).to_dict()

    try:
        _ensure_parent_dir(output_path)
        _write_pptx(
            output_path,
            title=title,
            bullet_points=bullet_points or [],
            content=content,
        )
        presented, present_error, presented_paths = await _try_present_path(
            ctx,
            output_path,
            auto_present=auto_present,
        )
        return _success_result(
            message=f"PPTX exported: {output_path.name}",
            requested_path=file_path,
            output_path=output_path,
            export_format="pptx",
            presented=presented,
            present_error=present_error,
            presented_relative_paths=presented_paths,
        )
    except Exception as e:
        return ToolResult.error(str(e), details={"file_path": file_path}).to_dict()


async def export_pdf_tool(
    ctx: "RunContext[SkillDeps]",
    file_path: str,
    title: str = "",
    content: str = "",
    auto_present: bool = True,
) -> dict:
    """Export plain text content into a PDF document."""
    try:
        output_path = _resolve_export_path(ctx, file_path, ".pdf")
    except ValueError as e:
        return ToolResult.error(str(e), details={"file_path": file_path}).to_dict()

    try:
        _ensure_parent_dir(output_path)
        _write_pdf(output_path, title=title, content=content)
        presented, present_error, presented_paths = await _try_present_path(
            ctx,
            output_path,
            auto_present=auto_present,
        )
        return _success_result(
            message=f"PDF exported: {output_path.name}",
            requested_path=file_path,
            output_path=output_path,
            export_format="pdf",
            presented=presented,
            present_error=present_error,
            presented_relative_paths=presented_paths,
        )
    except Exception as e:
        return ToolResult.error(str(e), details={"file_path": file_path}).to_dict()
